In [86]:
import torch
import numpy as np

In [87]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [88]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [89]:
y.grad_fn

In [90]:
z = y * y * 3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [91]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
b.grad_fn

False
True


In [92]:
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [95]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
    y = y*2 

y

tensor([ -224.6187,   926.5460, -1128.6174], grad_fn=<MulBackward0>)

In [97]:
v = torch.tensor([1e-1, 1, 1e-4])
y.backward(v)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [98]:
print(x.requires_grad)
y = x.detach()
y.requires_grad, x.eq(y).all()

True


(False, tensor(True))